# This docker-compose.yml file is used to set up your project in the local
# development environment *only*. It is *not* used in deployment to our cloud
# servers, and has no effect whatsoever in cloud deployments.
#
# See our Developer Handbook for more information:
# http://docs.divio.com/en/latest/reference/docker-docker-compose.html
version: '3.7'

services:

  # On the Cloud, your database runs on a dedicated cluster. Locally, we
  # replicate it in a Docker container called "db".
  db:
    environment:
      POSTGRES_DB: db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    image: postgres:9.6-alpine
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    build: 
      context: .
      dockerfile: Dockerfile.local
    # The default command that the container starts with. If you'd like to run
    # the project locally in Live configuration, you will need to change this.
    # See https://docs.divio.com/en/latest/how-to/local-in-live-mode.html.
    #command: [ "/opt/java/openjdk/bin/java", "-jar", "-Dspring.profiles.active=default", "./app.jar" ]
    command: [ "./scripts/run_dev.sh" ]
    depends_on:
      - db
    # Add any environment variables your project needs to the .env-local file.
    # See https://docs.divio.com/en/latest/reference/configuration-environment-variables.html.
    env_file: .env_local
    # Change the port if you'd like to expose your project locally on a
    # different port, for example if you already use port 8000 for
    # something else.
    ports: 
      - 8000:8080
    volumes:
      - ./src:/app/src

volumes:
  db-data:
